CREATE DATABASE LIBRO_MAYOR;
USE LIBRO_MAYOR;

CREATE TABLE MOVIMIENTOS
(
    NUM_MOVIMIENTO   INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    FECHA_MOVIMIENTO DATE,

    PRIMARY KEY (NUM_MOVIMIENTO)
);

/*ACTIVOS CIRCULANTES*/
CREATE TABLE BANCO
(
    MOVIMIENTO_BANCO INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_BANCO     FLOAT,
    ACREEDOR_BANCO   FLOAT,


    FOREIGN KEY (MOVIMIENTO_BANCO) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE CAPITAL_CONTABLE
(
    MOVIMIENTO_CAPITAL_CONTABLE INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_CAPITAL_CONTABLE     FLOAT,
    ACREEDOR_CAPITAL_CONTABLE   FLOAT,


    FOREIGN KEY (MOVIMIENTO_CAPITAL_CONTABLE) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE CAJA
(
    MOVIMIENTO_CAJA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_CAJA     FLOAT,
    ACREEDOR_CAJA   FLOAT,


    FOREIGN KEY (MOVIMIENTO_CAJA) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE ALMACEN
(
    MOVIMIENTO_ALMACEN INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_ALMACEN     FLOAT,
    ACREEDOR_ALMACEN   FLOAT,


    FOREIGN KEY (MOVIMIENTO_ALMACEN) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE TARJETA_ALMACEN
(
    MOVIMIENTO_TARJETA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    ENTRADAS_TARJETA   INT,
    SALIDAS_TARJETA    INT,
    EXISTENCIA_TARJETA INT,
    PRECIO_ADQUISICION FLOAT,
    PRECIO_PROMEDIO FLOAT,
    DEUDOR_TARJETA     FLOAT,
    ACREEDOR_TARJETA   FLOAT,

    FOREIGN KEY (MOVIMIENTO_TARJETA) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE CLIENTES
(
    MOVIMIENTO_CLIENTES INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_CLIENTES     FLOAT,
    ACREEDOR_CLIENTES   FLOAT,


    FOREIGN KEY (MOVIMIENTO_CLIENTES) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE DOC_POR_COBRAR
(
    MOVIMIENTO_DOC_POR_COBRAR INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_DOC_POR_COBRAR     FLOAT,
    ACREEDOR_DOC_POR_COBRAR   FLOAT,


    FOREIGN KEY (MOVIMIENTO_DOC_POR_COBRAR) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE DEUDORES_DIVERSOS
(
    MOVIMIENTO_DEUDORES_DIVERSOS INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_DEUDORES_DIVERSOS     FLOAT,
    ACREEDOR_DEUDORES_DIVERSOS   FLOAT,

    FOREIGN KEY (MOVIMIENTO_DEUDORES_DIVERSOS) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

/*Activos Fijos*/
CREATE TABLE TERRENOS
(
    MOVIMIENTO_TERRENOS INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_TERRENOS     FLOAT,
    ACREEDOR_TERRENOS   FLOAT,


    FOREIGN KEY (MOVIMIENTO_TERRENOS) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE EDIFICIOS
(
    MOVIMIENTO_EDIFICIOS INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_EDIFICIOS     FLOAT,
    ACREEDOR_EDIFICIOS   FLOAT,


    FOREIGN KEY (MOVIMIENTO_EDIFICIOS) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE MOB_Y_EQ_DE_OFICINA
(
    MOVIMIENTO_MOB_Y_EQ_DE_OFICINA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_MOB_Y_EQ_DE_OFICINA     FLOAT,
    ACREEDOR_MOB_Y_EQ_DE_OFICINA   FLOAT,


    FOREIGN KEY (MOVIMIENTO_MOB_Y_EQ_DE_OFICINA) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE EQ_DE_COMPUTO
(
    MOVIMIENTO_EQ_DE_COMPUTO INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_EQ_DE_COMPUTO     FLOAT,
    ACREEDOR_EQ_DE_COMPUTO   FLOAT,


    FOREIGN KEY (MOVIMIENTO_EQ_DE_COMPUTO) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE EQ_DE_REPARTO
(
    MOVIMIENTO_EQ_DE_REPARTO INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_EQ_DE_REPARTO     FLOAT,
    ACREEDOR_EQ_DE_REPARTO   FLOAT,


    FOREIGN KEY (MOVIMIENTO_EQ_DE_REPARTO) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE DEPOSITOS_EN_GARANTIA
(
    MOVIMIENTO_DEPOSITOS_EN_GARANTIA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_DEPOSITOS_EN_GARANTIA     FLOAT,
    ACREEDOR_DEPOSITOS_EN_GARANTIA   FLOAT,


    FOREIGN KEY (MOVIMIENTO_DEPOSITOS_EN_GARANTIA) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE ACCIONES_Y_VALORES
(
    MOVIMIENTO_ACCIONES_Y_VALORES INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_ACCIONES_Y_VALORES     FLOAT,
    ACREEDOR_ACCIONES_Y_VALORES   FLOAT,


    FOREIGN KEY (MOVIMIENTO_ACCIONES_Y_VALORES) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

/*ACRIVOS DIFERIDOS*/
CREATE TABLE GASTOS_DE_INSTALACION
(
    MOVIMIENTO_GASTOS_DE_INSTALACION INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_GASTOS_DE_INSTALACION     FLOAT,
    ACREEDOR_GASTOS_DE_INSTALACION   FLOAT,


    FOREIGN KEY (MOVIMIENTO_GASTOS_DE_INSTALACION) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE PAPELERIA_Y_UTILES
(
    MOVIMIENTO_PAPELERIA_Y_UTILES INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_PAPELERIA_Y_UTILES     FLOAT,
    ACREEDOR_PAPELERIA_Y_UTILES   FLOAT,


    FOREIGN KEY (MOVIMIENTO_PAPELERIA_Y_UTILES) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE PROPAGANDA_O_PUBLICIDAD
(
    MOVIMIENTO_PROPAGANDA_O_PUBLICIDAD INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_PROPAGANDA_O_PUBLICIDAD     FLOAT,
    ACREEDOR_PROPAGANDA_O_PUBLICIDAD   FLOAT,


    FOREIGN KEY (MOVIMIENTO_PROPAGANDA_O_PUBLICIDAD) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE PRIMAS_DE_SEGURO
(
    MOVIMIENTO_PRIMAS_DE_SEGURO INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_PRIMAS_DE_SEGURO     FLOAT,
    ACREEDOR_PRIMAS_DE_SEGURO   FLOAT,


    FOREIGN KEY (MOVIMIENTO_PRIMAS_DE_SEGURO) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE RENTAS_PAG_POR_ANT
(
    MOVIMIENTO_RENTAS_PAG_POR_ANT INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_RENTAS_PAG_POR_ANT     FLOAT,
    ACREEDOR_RENTAS_PAG_POR_ANT   FLOAT,


    FOREIGN KEY (MOVIMIENTO_RENTAS_PAG_POR_ANT) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE INTERESES_PAG_POR_ANT
(
    MOVIMIENTO_INTERESES_PAG_POR_ANT INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_INTERESES_PAG_POR_ANT     FLOAT,
    ACREEDOR_INTERESES_PAG_POR_ANT   FLOAT,


    FOREIGN KEY (MOVIMIENTO_INTERESES_PAG_POR_ANT) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

/*PASIVOS CIRCULANTES*/
CREATE TABLE PROVEEDORES
(
    MOVIMIENTO_PROVEEDORES INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_PROVEEDORES     FLOAT,
    ACREEDOR_PROVEEDORES   FLOAT,


    FOREIGN KEY (MOVIMIENTO_PROVEEDORES) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE DOC_POR_PAGAR
(
    MOVIMIENTO_DOC_POR_PAGAR INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_DOC_POR_PAGAR     FLOAT,
    ACREEDOR_DOC_POR_PAGAR   FLOAT,


    FOREIGN KEY (MOVIMIENTO_DOC_POR_PAGAR) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE ACREEDORES_DIVERSOS
(
    MOVIMIENTO_ACREEDORES_DIVERSOS INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_ACREEDORES_DIVERSOS     FLOAT,
    ACREEDOR_ACREEDORES_DIVERSOS   FLOAT,


    FOREIGN KEY (MOVIMIENTO_ACREEDORES_DIVERSOS) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

/*PASIVOS FIJOS*/
CREATE TABLE HIPOTECAS_POR_PAGAR
(
    MOVIMIENTO_HIPOTECAS_POR_PAGAR INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_HIPOTECAS_POR_PAGAR     FLOAT,
    ACREEDOR_HIPOTECAS_POR_PAGAR   FLOAT,


    FOREIGN KEY (MOVIMIENTO_HIPOTECAS_POR_PAGAR) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE DOC_POR_PAGAR_LP
(
    MOVIMIENTO_DOC_POR_PAGAR_LP INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_DOC_POR_PAGAR_LP     FLOAT,
    ACREEDOR_DOC_POR_PAGAR_LP   FLOAT,


    FOREIGN KEY (MOVIMIENTO_DOC_POR_PAGAR_LP) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

/*PASIVOS DIFERIDOS*/
CREATE TABLE RENTAS_COBRADAS_POR_ANT
(
    MOVIMIENTO_RENTAS_COBRADAS_POR_ANT INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_RENTAS_COBRADAS_POR_ANT     FLOAT,
    ACREEDOR_RENTAS_COBRADAS_POR_ANT   FLOAT,


    FOREIGN KEY (MOVIMIENTO_RENTAS_COBRADAS_POR_ANT) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE INTERESES_COBRADOS_POR_ANT
(
    MOVIMIENTO_INTERESES_COBRADOS_POR_ANT INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_INTERESES_COBRADOS_POR_ANT     FLOAT,
    ACREEDOR_INTERESES_COBRADOS_POR_ANT   FLOAT,


    FOREIGN KEY (MOVIMIENTO_INTERESES_COBRADOS_POR_ANT) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

/*CUENTAS DE RESULTADO*/
CREATE TABLE VENTAS_NETAS
(
    MOVIMIENTO_VENTAS_NETAS INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_VENTAS_NETAS     FLOAT,
    ACREEDOR_VENTAS_NETAS   FLOAT,


    FOREIGN KEY (MOVIMIENTO_VENTAS_NETAS) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE COSTO_DE_VENTA
(
    MOVIMIENTO_COSTO_DE_VENTA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_COSTO_DE_VENTA     FLOAT,
    ACREEDOR_COSTO_DE_VENTA   FLOAT,


    FOREIGN KEY (MOVIMIENTO_COSTO_DE_VENTA) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE GASTO_DE_VENTA
(
    MOVIMIENTO_GASTO_DE_VENTA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_GASTO_DE_VENTA     FLOAT,
    ACREEDOR_GASTO_DE_VENTA   FLOAT,


    FOREIGN KEY (MOVIMIENTO_GASTO_DE_VENTA) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE GASTO_DE_ADMON
(
    MOVIMIENTO_GASTO_DE_ADMON INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_GASTO_DE_ADMON     FLOAT,
    ACREEDOR_GASTO_DE_ADMON   FLOAT,


    FOREIGN KEY (MOVIMIENTO_GASTO_DE_ADMON) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE GASTOS_Y_PROD_FINAN
(
    MOVIMIENTO_GASTOS_Y_PROD_FINAN INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_GASTOS_Y_PROD_FINAN     FLOAT,
    ACREEDOR_GASTOS_Y_PROD_FINAN   FLOAT,


    FOREIGN KEY (MOVIMIENTO_GASTOS_Y_PROD_FINAN) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE OTROS_GASTOS_OTROS_PROD
(
    MOVIMIENTO_OTROS_GASTOS_OTROS_PROD INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_OTROS_GASTOS_OTROS_PROD     FLOAT,
    ACREEDOR_OTROS_GASTOS_OTROS_PROD   FLOAT,


    FOREIGN KEY (MOVIMIENTO_OTROS_GASTOS_OTROS_PROD) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE GASTO_ISR
(
    MOVIMIENTO_GASTO_ISR INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_GASTO_ISR     FLOAT,
    ACREEDOR_GASTO_ISR   FLOAT,


    FOREIGN KEY (MOVIMIENTO_GASTO_ISR) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE GASTO_PTU
(
    MOVIMIENTO_GASTO_PTU INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_GASTO_PTU     FLOAT,
    ACREEDOR_GASTO_PTU   FLOAT,


    FOREIGN KEY (MOVIMIENTO_GASTO_PTU) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);

CREATE TABLE PERDIDAS_Y_GANANCIAS
(
    MOVIMIENTO_PERDIDAS_Y_GANANCIAS INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    DEUDOR_PERDIDAS_Y_GANANCIAS     FLOAT,
    ACREEDOR_PERDIDAS_Y_GANANCIAS   FLOAT,


    FOREIGN KEY (MOVIMIENTO_PERDIDAS_Y_GANANCIAS) REFERENCES MOVIMIENTOS (NUM_MOVIMIENTO)
);